// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// infer_cpp
Rcpp::List infer_cpp();
RcppExport SEXP _BORIS_infer_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(infer_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sim_cpp
Rcpp::List sim_cpp();
RcppExport SEXP _BORIS_sim_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(sim_cpp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BORIS_infer_cpp", (DL_FUNC) &_BORIS_infer_cpp, 0},
    {"_BORIS_sim_cpp", (DL_FUNC) &_BORIS_sim_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BORIS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
