# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

infer_cpp <- function() {
    .Call(`_BORIS_infer_cpp`)
}

sim_cpp <- function() {
    .Call(`_BORIS_sim_cpp`)
}

